presubmits:
  - name: pull-kcp-verify
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/kcp"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.22.2-1
          command:
            - make
            - verify-boilerplate
            - verify-modules
            - verify-k8s-deps
            - verify-imports
          resources:
            requests:
              memory: 1Gi
              cpu: 1

  - name: pull-gco-lint
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/kcp"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.22.2-1
          command:
            - make
            - lint
          resources:
            requests:
              memory: 4Gi
              cpu: 2

  - name: pull-gcp-build-image
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/generic-controlplane"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/containers/buildah:v1.30.0
          command:
            - hack/build-image.sh
          env:
            - name: DRY_RUN
              value: '1'
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 1Gi
              cpu: 1

  - name: pull-gcp-test-unit
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/generic-controlplane"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.22.2-1
          command:
            - make
            - test
          env:
            - name: USE_GOTESTSUM
              value: '1'
          resources:
            requests:
              memory: 4Gi
              cpu: 2

